language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install pep8
  - pep8 --exclude=tests *.py cnxml
  - pep8 --max-line-length=200 cnxml/tests

  - pip install --upgrade setuptools
  - pip install --upgrade pip
  # Install the coverage utility and coveralls reporting utility
  - pip install pytest-cov
  - pip install codecov
install:
  # Install test requirements
  - pip install -e ".[test]"
  # Now install it as a standalone distribution
  - pip uninstall -y .
  - pip install .
script:
  - py.test
after_success:
  - coverage report
  # Report test coverage to codecov.io
  - codecov
notifications:
  email: false
