language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install flake8
  - flake8 --exclude=tests cnxml
  - flake8 --max-line-length=200 cnxml/tests

  - pip install --upgrade setuptools
  - pip install --upgrade pip
  # Install the coverage utility and coveralls reporting utility
  - pip install pytest-cov
  - pip install codecov
install:
  # Install test requirements
  - pip install ".[test]"
script:
  - py.test
after_success:
  - coverage report
  # Report test coverage to codecov.io
  - codecov
notifications:
  email: false
